sudo: required

language: go

services:
  - docker

install:
  - vendor/go-bindata-Linux -pkg constants -o constants/assets.go ./schema/0.1.0/

script:
  - ./build-cli.sh ${TRAVIS_TAG}
  - go test ./...

deploy:
  # Deployment that pushes GitHub releases of software on tag
  - provider: releases
    api_key: "$GH_TOKEN"
    file_glob: true
    file: output/*
    skip_cleanup: true
    on:
      tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/10070a680400c55e3baa
    on_success: change
    on_failure: always
    on_start: never
